# This is used to config the canvas doain
test:
  domain: localhost

development:
  domain: '127.0.0.1:8443' #We use 8443 since we use HA proxy
  # If you want to set up SSL and a separate files domain, use the following and set up puma-dev from github.com/puma/puma-dev
  # domain: "canvas-lms.test" # for puma-dev
  # files_domain: "canvas-lms.files" # for puma-dev
  ssl: true

production:
  domain: 'canvas-prod.coasterfan5.com'
  # whether this instance of canvas is served over ssl (https) or not
  # defaults to true for production, false for test/development
  ssl: true
  # files_domain: "canvasfiles.example.com"
